export { default as Home } from './Home'
export { default as Curricula } from './Curricula'
export { default as FeedBacks } from './FeedBacks'
export { default as Students } from './Students'
export { default as Groups } from './Groups'
export { default as Lectures } from './Lectures'
export { default as Layout } from './Layout'
